### ISSUE TITLE
Add RegEx to redirect match operators

### ISSUE THREAD

**Issue by KamikyIT** [vvmgev/Inssman#12]
Can you add RegEx to redirect match operators?

Or how can I achieve following behaviour with already exist methods?

For example, I want to redirect

google.com/project/123/temp
to
localhost/myproject/123/temp
with any parameters of "123"

**Comment by vvmgev** [comment]
@KamikyIT 

Now the extension also supports the **wildcard** match operator.
<img width="1138" alt="Screenshot 2023-07-29 at 22 39 51" src="https://github.com/vvmgev/Inssman/assets/11613729/0ae10d3f-2d04-432d-b328-9f447f5e06c8">

Please make sure you are using the last version of an extension
