### ISSUE TITLE
[Feature request] Multiple redirects per one rule

### ISSUE THREAD

**Issue by mouettxy** [vvmgev/Inssman#21]
For example this how it's done in requestly

![image](https://github.com/vvmgev/Inssman/assets/32680159/bd7d22f3-4e37-41b8-b2e4-f012d99f9f01)

This is existing UI that we can reuse

![image](https://github.com/vvmgev/Inssman/assets/32680159/0147d8da-6b91-4c1e-b9cc-240039bda9c3)

If you don't mind I could submit, a PR with those changes

**Comment by vvmgev** [comment]
Hello @mouettxy 

Thank you so much for the suggestion. This feature is in the backlog, but if you can open a merge request (MR), it will speed up the development.

Thank you again

**Comment by vvmgev** [comment]
At this moment it is possible to have multiple conditions
