### ISSUE TITLE
Feature request: Add "X-Forwarded-For" to keys

### ISSUE THREAD

**Issue by AKXF2020** [vvmgev/Inssman#22]
No auto tip for XFF now.
![Snipaste_2023-12-05_21-08-22](https://github.com/vvmgev/Inssman/assets/63178001/3705f39b-f43c-4761-9aeb-88db60348c94)

**Comment by vvmgev** [comment]
@AKXF2020 
Dear @AKXF2020 

Thank you so much for creating the feature request.

The upcoming version(1.0.61) includes the header.
