### ISSUE TITLE
Is it possible or not to replace the specific targeted part of the request body or response? similar to the section on "Query Param."

### ISSUE THREAD

**Issue by chalitguza** [vvmgev/Inssman#32]
Instead of replacing the entire content, Is it possible or not to replace the specific targeted part of the request body or response? similar to the section on "Query Param."

For example:

//old
```
{
  "text": "abc123"
}
```

//new (Replace the specific targeted portion of the content.)
```
{
  "text": "test"
}
```

**Comment by vvmgev** [comment]
@chalitguza Thank you for requesting this feature

Version 1.0.59 has a new feature.
It is possible to modify the response dynamically.


<img width="1008" alt="Screenshot 2024-03-07 at 13 47 30" src="https://github.com/vvmgev/Inssman/assets/11613729/bd87130b-7b59-43cb-b600-4fbb9b45c142">
