### ISSUE TITLE
Cannot paste in static response text area

### ISSUE THREAD

**Issue by jimtonnpolaris** [vvmgev/Inssman#45]
1. Open extension
2. Go to Modify Response in left menu
3. Make sure Static Response is selected
4. Copy some text to clipboard and confirm that it is present by pasting it into another application
5. In the static response text area, use Ctrl-V or the right-click menu->Paste to paste the text.
Expected: The text appears in the text area.
Actual: The text does not appear in the text area.

**Comment by Cheese-Yu** [comment]
Refer: https://github.com/suren-atoyan/monaco-react/issues/606

**Comment by vvmgev** [comment]
Fixed!

**Comment by lucasccampos** [comment]
Issue is back! can't paste it
