### ISSUE TITLE
Why does the installation directory have so many subdirectories？

### ISSUE THREAD

**Issue by a991e** [vvmgev/Inssman#5]
there are so many subdirectories which named numerically.
![2023-04-09_1](https://user-images.githubusercontent.com/37282378/230772516-3c5c00df-002f-4848-a866-3fd2bc35aa37.jpg)

**Comment by vvmgev** [comment]
@a991e 
The extension uses [Monaco](https://microsoft.github.io/monaco-editor/) for installation, which creates multiple folders. However, it is planned to be replaced with a lightweight editor in the near future.
