### ISSUE TITLE
Rules 

### ISSUE THREAD

**Issue by jsbianxiang** [vvmgev/Inssman#7]
![image](https://user-images.githubusercontent.com/16028279/235371291-556ede56-329e-4d06-a798-4423599ac37d.png)
Your extensions are easy to use and the instructions are easy to understand.
Whether all rules can be exported. Need your help

**Comment by vvmgev** [comment]
@jsbianxiang 
Unfortunately, currently, there is no way to import or export rules. However, it is planned to introduce the ability to import and export rules in the near future, making it more convenient for users.
